# Generated by Django 2.2.2 on 2019-07-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=0)),
                ('question', models.TextField()),
                ('optionOne', models.CharField(max_length=150)),
                ('optionTne', models.CharField(max_length=150)),
                ('optionThree', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='test_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='', max_length=75)),
                ('description', models.CharField(default='', max_length=150)),
                ('isSCT_test', models.BooleanField()),
                ('SCTSteam', models.CharField(default='', max_length=150)),
                ('SCTBranch', models.CharField(default='', max_length=150)),
                ('SCTSemester', models.CharField(default='', max_length=10)),
                ('TestDifficulty', models.CharField(default='', max_length=75)),
                ('category_level', models.CharField(default='', max_length=75)),
                ('steam', models.CharField(default='', max_length=25)),
                ('category_one', models.CharField(default='', max_length=25)),
                ('category_two', models.CharField(default='', max_length=75)),
                ('category_three', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='Created', max_length=50)),
                ('added_by', models.CharField(default='', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='test_details_advanced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=75)),
                ('isTimer', models.BooleanField()),
                ('TimerLength', models.CharField(default='0', max_length=50)),
                ('isAvailDuration', models.BooleanField()),
                ('DurationFrom', models.CharField(default='0', max_length=75)),
                ('DurationTo', models.CharField(default='0', max_length=25)),
                ('sendNotification', models.CharField(default='', max_length=25)),
                ('NotificationSettings', models.CharField(default='Dont Send', max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
