# Generated by Django 2.2.2 on 2019-07-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='SCTSemester',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_details',
            name='TestDifficulty',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='test_details',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test_details',
            name='category_level',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='test_details',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='test_details',
            name='test_name',
            field=models.CharField(max_length=75),
        ),
    ]
