# Generated by Django 2.2.2 on 2019-07-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0002_auto_20190720_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='SCTSemester',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='test_details',
            name='category_one',
            field=models.CharField(default='', max_length=75),
        ),
    ]
