# Generated by Django 2.2.2 on 2019-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0003_auto_20190720_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_data',
            old_name='optionTne',
            new_name='optionTwo',
        ),
        migrations.AddField(
            model_name='test_data',
            name='optionFour',
            field=models.CharField(default='', max_length=150),
        ),
    ]
