# Generated by Django 2.2.2 on 2019-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0004_auto_20190725_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='AskQuestion',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='test_details',
            name='TestType',
            field=models.CharField(default='', max_length=75),
        ),
    ]
