# Generated by Django 2.2.2 on 2019-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0005_auto_20190728_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='resumeable',
            field=models.BooleanField(default=True),
        ),
    ]
