# Generated by Django 2.2.2 on 2019-08-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0006_test_details_resumeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='ask',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='test_details',
            name='ask_number',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='test_details',
            name='movetopractice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test_details',
            name='ranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test_details',
            name='shuffle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test_details',
            name='sreport',
            field=models.BooleanField(default=True),
        ),
    ]
