# Generated by Django 2.2.2 on 2019-08-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0007_auto_20190822_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_details',
            name='ask_number',
        ),
    ]
