# Generated by Django 2.2.2 on 2019-08-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0008_remove_test_details_ask_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='MarkingSetting',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test_details',
            name='QuestionType',
            field=models.CharField(default='Standard', max_length=75),
        ),
        migrations.AddField(
            model_name='test_details',
            name='QuestionUploaded',
            field=models.BooleanField(default=False),
        ),
    ]
