# Generated by Django 2.2.2 on 2019-08-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0009_auto_20190823_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='QuestionType',
            field=models.CharField(default='', max_length=75),
        ),
    ]
