# Generated by Django 2.2.2 on 2019-08-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0010_auto_20190823_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=75)),
                ('status', models.CharField(max_length=100)),
                ('exam_session', models.CharField(max_length=250)),
                ('InformedStudents', models.BooleanField(default=False)),
            ],
        ),
    ]
