# Generated by Django 2.2.2 on 2019-08-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0011_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='program',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='sem',
            field=models.CharField(default='', max_length=100),
        ),
    ]
