# Generated by Django 2.2.2 on 2019-08-24 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0012_auto_20190824_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
