# Generated by Django 2.2.2 on 2019-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0013_exam_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='test_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
