# Generated by Django 2.2.2 on 2019-08-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0014_exam_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='outside_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
