# Generated by Django 2.2.2 on 2019-07-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steam_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.IntegerField()),
                ('steam_data_json', models.TextField()),
                ('multilevel_data', models.BooleanField()),
                ('steam_status', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='steam',
            name='steam_link_id',
            field=models.IntegerField(),
        ),
    ]
