# Generated by Django 2.2.2 on 2019-07-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0002_auto_20190703_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam_data',
            name='multilevel_data',
            field=models.CharField(max_length=25),
        ),
    ]
