# Generated by Django 2.2.2 on 2019-08-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=250)),
                ('test_useremail', models.CharField(max_length=250)),
                ('test_istimer', models.BooleanField()),
                ('timer_duration', models.CharField(max_length=20)),
                ('scored', models.CharField(max_length=20)),
                ('total_score', models.CharField(max_length=20)),
                ('TestType', models.CharField(max_length=20)),
                ('resumeable', models.BooleanField()),
            ],
        ),
    ]
