# Generated by Django 2.2.2 on 2019-08-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='FirstOpen',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='details',
            name='TestID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='TestType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='scored',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='test_session_id',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='details',
            name='test_useremail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='details',
            name='timer_duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='total_score',
            field=models.CharField(default='', max_length=20),
        ),
    ]
