# Generated by Django 2.2.2 on 2019-08-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_test', '0004_auto_20190813_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='FirstOpen',
        ),
    ]
