# Generated by Django 2.2.2 on 2019-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_test', '0005_remove_details_firstopen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='resumeable',
        ),
        migrations.AlterField(
            model_name='details',
            name='test_istimer',
            field=models.BooleanField(default=False),
        ),
    ]
