# Generated by Django 2.2.2 on 2019-08-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_test', '0006_auto_20190813_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='test_istimer',
        ),
    ]
