# Generated by Django 2.2.2 on 2019-08-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_test', '0008_auto_20190813_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='resumeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='test_istimer',
            field=models.BooleanField(default=True),
        ),
    ]
