# Generated by Django 2.2.2 on 2019-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_test', '0009_auto_20190813_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='resumeable',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='test_istimer',
            field=models.CharField(default='', max_length=20),
        ),
    ]
