# Generated by Django 2.2.2 on 2019-08-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_test', '0010_auto_20190813_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
