# Generated by Django 2.2.2 on 2019-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_session', models.BooleanField()),
                ('session_from', models.DateField()),
                ('session_to', models.DateField()),
                ('status', models.CharField(max_length=75)),
            ],
        ),
    ]
