# Generated by Django 2.2.2 on 2019-08-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_status', models.BooleanField()),
                ('program', models.CharField(max_length=100)),
                ('option_txt', models.TextField()),
                ('branch', models.CharField(max_length=100)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_manager.details')),
            ],
        ),
        migrations.CreateModel(
            name='data_semseter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_status', models.BooleanField()),
                ('duration_type', models.CharField(max_length=100)),
                ('duration_number', models.CharField(max_length=100)),
                ('ClassTeacher_ID', models.CharField(max_length=100)),
                ('option_txt', models.TextField()),
                ('HOD_ID', models.CharField(max_length=100)),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_manager.data')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_manager.details')),
            ],
        ),
        migrations.CreateModel(
            name='academic_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('from_ay', models.CharField(max_length=100)),
                ('to_ay', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=500)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_manager.details')),
            ],
        ),
    ]
