# Generated by Django 2.2.2 on 2019-08-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_content_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=75)),
                ('creation_session', models.CharField(max_length=250)),
                ('filename', models.CharField(max_length=250)),
                ('upload', models.FileField(upload_to='')),
                ('actual_filename', models.CharField(max_length=250)),
                ('extension', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='creation_session',
            field=models.CharField(default='', max_length=75),
        ),
    ]
