# Generated by Django 2.2.2 on 2019-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190817_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='upload',
            field=models.FileField(upload_to='upload_attachment/%Y/%m/%d/'),
        ),
    ]
