# Generated by Django 2.2.2 on 2019-08-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190817_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='upload',
            field=models.FileField(upload_to='upload_attachment/'),
        ),
    ]
