# Generated by Django 2.2.2 on 2019-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=75)),
                ('website_description', models.CharField(max_length=250)),
                ('timezone', models.CharField(max_length=25)),
                ('salt', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='')),
                ('favicon', models.ImageField(upload_to='')),
                ('student_signup', models.BooleanField()),
                ('sms_notification', models.BooleanField()),
                ('email_notification', models.BooleanField()),
                ('smtp_host', models.CharField(max_length=75)),
                ('smtp_port', models.IntegerField(max_length=5)),
                ('smtp_email', models.CharField(max_length=75)),
                ('smtp_username', models.CharField(max_length=75)),
                ('smtp_password', models.CharField(max_length=75)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
