# Generated by Django 2.2.2 on 2019-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email_notification',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(upload_to='favicon/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sms_notification',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtp_port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='student_signup',
            field=models.CharField(max_length=10),
        ),
    ]
