# Generated by Django 2.2.2 on 2019-07-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_user',
            name='otp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
