# Generated by Django 2.2.2 on 2019-07-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_student_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_user',
            name='date_of_birth',
            field=models.CharField(default='', max_length=25),
        ),
    ]
