# Generated by Django 2.2.2 on 2019-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_student_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_academic',
            name='profile',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
