# Generated by Django 2.2.2 on 2019-07-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_student_academic_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_academic',
            name='student_email',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='student_dashboard_metrices',
            name='student_email',
            field=models.CharField(default='', max_length=75),
        ),
    ]
