# Generated by Django 2.2.2 on 2019-07-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20190727_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_academic',
            name='subject_preference',
            field=models.TextField(),
        ),
    ]
