# Generated by Django 2.2.2 on 2019-08-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20190727_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_academic',
            name='ClgStatus',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='student_academic',
            name='EnrollNo',
            field=models.CharField(default='', max_length=75),
        ),
    ]
