# Generated by Django 2.2.2 on 2019-07-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch_degree',
            old_name='branch_name',
            new_name='degree_name',
        ),
        migrations.RenameField(
            model_name='branch_degree',
            old_name='branch_status',
            new_name='degree_status',
        ),
    ]
