# Generated by Django 2.2.2 on 2019-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_auto_20190711_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchs',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='branchs',
            name='degree_name',
            field=models.CharField(max_length=100),
        ),
    ]
