# Generated by Django 2.2.2 on 2019-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20190711_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchs',
            name='degree_name',
        ),
        migrations.AddField(
            model_name='branchs',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branchs',
            name='program',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branchs',
            name='semester',
            field=models.CharField(default='', max_length=100),
        ),
    ]
