# Generated by Django 2.2.2 on 2019-07-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('desination', models.CharField(max_length=75)),
                ('department', models.CharField(max_length=75)),
                ('epployee_id', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
