# Generated by Django 2.2.2 on 2019-09-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='avatar',
            field=models.ImageField(default='/static/teacher/assets/img/avatar.png', upload_to=''),
        ),
    ]
