# Generated by Django 2.2.2 on 2019-07-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('lastname', models.IntegerField()),
                ('employe_id', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('phone_no', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
