# Generated by Django 2.2.2 on 2019-07-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='added_by_user',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(max_length=75),
        ),
    ]
