# Generated by Django 2.2.2 on 2019-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Admin', '0003_auto_20190708_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=75)),
                ('activity_name', models.CharField(max_length=75)),
                ('activity_des', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
