# Generated by Django 2.2.2 on 2019-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='start_test_details',
            name='test_settings',
            field=models.TextField(default=''),
        ),
    ]
