# Generated by Django 2.2.2 on 2019-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0003_start_test_details_test_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start_test_details',
            name='test_started',
            field=models.DateTimeField(),
        ),
    ]
