# Generated by Django 2.2.2 on 2019-08-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0005_auto_20190814_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='start_test_details',
            name='TestStatus',
            field=models.CharField(default='Started', max_length=20),
        ),
    ]
