# Generated by Django 2.2.2 on 2019-08-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0006_start_test_details_teststatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='submited_test_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=250)),
                ('test_useremail', models.CharField(max_length=250)),
                ('test_started', models.DateTimeField(auto_now_add=True)),
                ('test_submited', models.CharField(max_length=20)),
                ('submited_det', models.TextField()),
                ('scored', models.CharField(max_length=20)),
                ('total_score', models.CharField(max_length=20)),
                ('correct', models.CharField(max_length=20)),
                ('wrong', models.CharField(max_length=20)),
                ('clg_rnk', models.CharField(max_length=20)),
                ('class_rnk', models.CharField(max_length=20)),
                ('TestStatus', models.CharField(default='Submited', max_length=20)),
            ],
        ),
    ]
