# Generated by Django 2.2.2 on 2019-08-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0007_submited_test_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submited_test_report',
            name='class_rnk',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='submited_test_report',
            name='clg_rnk',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='submited_test_report',
            name='scored',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='submited_test_report',
            name='total_score',
            field=models.CharField(default='', max_length=20),
        ),
    ]
