# Generated by Django 2.2.2 on 2019-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0008_auto_20190815_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submited_test_report',
            name='test_started',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='submited_test_report',
            name='test_submited',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
