# Generated by Django 2.2.2 on 2019-08-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0009_auto_20190815_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='start_exam_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=250)),
                ('test_useremail', models.CharField(max_length=250)),
                ('test_istimer', models.BooleanField()),
                ('timer_duration', models.CharField(max_length=20)),
                ('test_started', models.DateTimeField(auto_now_add=True)),
                ('test_settings', models.TextField(default='')),
                ('scored', models.CharField(max_length=20)),
                ('total_score', models.CharField(max_length=20)),
                ('TestType', models.CharField(max_length=20)),
                ('TestID', models.CharField(max_length=20)),
                ('resumeable', models.BooleanField()),
                ('TestStarted', models.BooleanField()),
                ('TestStatus', models.CharField(default='Started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='submited_exam_individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=250)),
                ('test_useremail', models.CharField(max_length=250)),
                ('appear_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('question_anw_json', models.TextField()),
                ('obtained_scored', models.CharField(default='', max_length=20)),
                ('total_score', models.CharField(default='', max_length=20)),
                ('is_correct', models.CharField(max_length=20)),
                ('TestStatus', models.CharField(default='Submited', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='submited_exam_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=250)),
                ('test_useremail', models.CharField(max_length=250)),
                ('test_started', models.DateTimeField()),
                ('test_submited', models.DateTimeField(auto_now_add=True)),
                ('submited_det', models.TextField()),
                ('scored', models.CharField(default='', max_length=20)),
                ('total_score', models.CharField(default='', max_length=20)),
                ('correct', models.CharField(max_length=20)),
                ('wrong', models.CharField(max_length=20)),
                ('clg_rnk', models.CharField(default='', max_length=20)),
                ('class_rnk', models.CharField(default='', max_length=20)),
                ('TestStatus', models.CharField(default='Submited', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='submited_test_individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=250)),
                ('test_useremail', models.CharField(max_length=250)),
                ('appear_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('question_anw_json', models.TextField()),
                ('obtained_scored', models.CharField(default='', max_length=20)),
                ('total_score', models.CharField(default='', max_length=20)),
                ('is_correct', models.CharField(max_length=20)),
                ('TestStatus', models.CharField(default='Submited', max_length=20)),
            ],
        ),
    ]
