# Generated by Django 2.2.2 on 2019-08-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0010_start_exam_details_submited_exam_individual_submited_exam_report_submited_test_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='start_exam_details',
            name='ExamID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
