# Generated by Django 2.2.2 on 2019-08-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0011_start_exam_details_examid'),
    ]

    operations = [
        migrations.AddField(
            model_name='start_exam_details',
            name='HallAttendence',
            field=models.BooleanField(default=True),
        ),
    ]
