# Generated by Django 2.2.2 on 2019-08-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0012_start_exam_details_hallattendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='real_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=250)),
                ('test_useremail', models.CharField(max_length=250)),
                ('TestID', models.CharField(max_length=20)),
                ('ExamID', models.CharField(default='', max_length=20)),
                ('TotalQuestion', models.CharField(default='', max_length=20)),
                ('QuestionChecked', models.CharField(default='', max_length=20)),
                ('QuestionNumber', models.CharField(default='', max_length=20)),
                ('TestStatus', models.CharField(default='', max_length=20)),
                ('started_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='start_exam_details',
            name='ExamID',
        ),
        migrations.RemoveField(
            model_name='start_exam_details',
            name='TestID',
        ),
    ]
