# Generated by Django 2.2.2 on 2019-08-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0013_auto_20190826_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='start_exam_details',
            name='ExamID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='start_exam_details',
            name='TestID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
