# Generated by Django 2.2.2 on 2019-08-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0014_auto_20190826_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='start_exam_details',
            name='ResultStatus',
            field=models.CharField(default='', max_length=20),
        ),
    ]
