# Generated by Django 2.2.2 on 2019-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0015_start_exam_details_resultstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='start_exam_details',
            name='ResultStatus',
        ),
        migrations.AddField(
            model_name='submited_exam_report',
            name='ResultStatus',
            field=models.CharField(default='', max_length=20),
        ),
    ]
