# Generated by Django 2.2.2 on 2019-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0016_auto_20190826_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_realtime_each_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=250)),
                ('test_useremail', models.CharField(max_length=250)),
                ('question_count', models.CharField(max_length=10)),
                ('question_number', models.CharField(max_length=10)),
                ('test_started', models.DateTimeField(auto_now_add=True)),
                ('test_last_update', models.DateTimeField(auto_now_add=True)),
                ('check_ans_number', models.CharField(max_length=100)),
                ('TestID', models.CharField(default='', max_length=75)),
                ('ExamID', models.CharField(default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='exam_realtime_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=250)),
                ('test_useremail', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
    ]
