# Generated by Django 2.2.2 on 2019-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0017_exam_realtime_each_question_exam_realtime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_realtime_user',
            name='ExamID',
            field=models.CharField(default='', max_length=250),
        ),
    ]
