# Generated by Django 2.2.2 on 2019-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0018_exam_realtime_user_examid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submited_exam_report',
            name='ExamID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='submited_exam_report',
            name='TestID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
