# Generated by Django 2.2.2 on 2019-09-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_test_info', '0019_auto_20190830_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='submited_test_report',
            name='ResultStatus',
            field=models.CharField(default='', max_length=20),
        ),
    ]
