# Generated by Django 2.2.2 on 2019-08-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=75)),
                ('status', models.CharField(max_length=75)),
                ('announcement_type', models.CharField(max_length=100)),
                ('send_to_group', models.CharField(max_length=100)),
                ('sendto_ids_json', models.TextField()),
                ('attachment_file', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=250)),
                ('ischedule', models.BooleanField()),
                ('schedule_date', models.DateField()),
                ('date', models.DateField()),
            ],
        ),
    ]
